Create user Environment with mambaforge
UBA-DE-Emissionsituation/space-emissions pull request #29
Opened 2021-07-02 07:41 UTC by Christian-Mielke

This docstring explains the creation of the neccessary Python 3.9 user environment for space-emissions. So there should be no pipenv file needed. I hope the instructions are clear enough that even mainly GUI users may setup their envs correctly using the console.

2021-07-05 13:18 UTC, Christian-Mielke commented
Okay I included the sentinel and cdsapi as hinted by Janot

2021-07-05 19:43 UTC, kevin-hausmann commented
I tested this in a Xubuntu virtual machine and it works great!

2021-07-05 19:46 UTC, kevin-hausmann requested changes
I think this is great and it works well. Please improve the formatting a bit and you are good to go...

2021-07-05 19:46 UTC, kevin-hausmann commented on INSTALL.md
> +The shorthand version would be: [`mamba create -n py39spaceborne python=3.9 jupyterlab gdal geopandas shapely numpy rtree pyproj contextily pytest sentinelsat cdsapi requests`]
Does this shorthand version actually work? I think the channel info is missing?

2021-07-05 19:46 UTC, kevin-hausmann commented on INSTALL.md
> +In order to use the spaceborne-emission calculator efficiently also on your platform we would reccommend the usage of the "Fast Cross-Platform Package Manager" [Mamba](https://github.com/mamba-org/ma
```suggestion
In order to use the spaceborne-emission calculator efficiently also on your platform we would reccommend the usage of the "Fast Cross-Platform Package Manager" [Mamba](https://github.com/mamba-org/mamba), which will handle all the necessary dependencies for the spaceborne-emmission calculator following the setup procedure described here from scratch:
```

2021-07-06 09:39 UTC, Christian-Mielke commented on INSTALL.md
> +The shorthand version would be: [`mamba create -n py39spaceborne python=3.9 jupyterlab gdal geopandas shapely numpy rtree pyproj contextily pytest sentinelsat cdsapi requests`]
This is how I installed it on my windows machine. If you use the Miniforge distribution (e.g. ond windows) your default channel is conda-forge anyway. So one could leave that out. But I would say leave it in. This way users awareness is risen about that there is such a thing called software channels. Most users who are interested would search for the term "Software channels mamba", whilst many users would just be happy copy and paste the shorthand version.

2021-07-06 10:09 UTC, kevin-hausmann approved these changes

2021-07-07 13:04 UTC, enricodammers requested changes
Clear enough to me,

Do change "reccommend " to recommend.
So only a veryy a minor thing, otherwise approved.

2021-07-07 13:11 UTC, jptokaya approved these changes
Clear enough and works for me :)

2021-07-07 17:02 UTC, Christian-Mielke commented
Change done

2021-07-08 06:49 UTC, enricodammers approved these changes

2021-07-08 06:53 UTC, kevin-hausmann requested changes
I think the main README.md should reference this file, can you include that?

2021-07-08 07:27 UTC, Christian-Mielke commented
> I think the main README.md should reference this file, can you include that?

done

2021-07-08 19:25 UTC, merged